services: mongodb

script: "bundle exec rake spec"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby
  - rbx

gemfile:
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_edge.gemfile
  - gemfiles/data_mapper_12.gemfile
  - gemfiles/mongo_mapper.gemfile
  - gemfiles/mongoid_31.gemfile
  - gemfiles/mongoid_40.gemfile
  - gemfiles/sinatra_14.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - gemfile: gemfiles/mongoid_40.gemfile
    - gemfile: gemfile/active_record_edge.gemfile
  fast_finish: true
